version: "3.7"
services:
  app:
    build:
      args:
        user: protoshell
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecommerce_laravel
    container_name: ecommerce_laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ecommerce_laravel

  nginx:
    image: nginx:alpine
    container_name: ecommerce_laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ecommerce_laravel

networks:
  ecommerce_laravel:
    driver: bridge